print(int())
print(int(100))
print(float())
print(float(35.3))
print(bool())
print(bool(1))
print(complex())
print(complex())
print(str())
print(str("state"))
print(list())
print(list(["a", "e", "i"]))
print(tuple())
print(tuple(("filipe", 35, 65.2, ["father", "grappler", "developer", "christian"], { "married" : False})))
print(dict())
print(dict({"steps" : 6.500, "heart-points" : 200}))
